Repository CS2103-AY1819S1-W17-2/main, pull requests merged in 2018-11, with the labels that each got.

#228 User Account Management: Logout Command
  src/main/java/seedu/modsuni/commons/events/ui/UserTabChangedEvent.java
  src/main/java/seedu/modsuni/commons/events/ui/UserTabLogoutEvent.java
  src/main/java/seedu/modsuni/logic/CommandHistory.java
  src/main/java/seedu/modsuni/logic/commands/LogoutCommand.java
  src/main/java/seedu/modsuni/logic/parser/ModsUniParser.java
  src/main/java/seedu/modsuni/model/Model.java
  src/main/java/seedu/modsuni/model/ModelManager.java
  src/main/java/seedu/modsuni/ui/UserTab.java
  src/test/java/seedu/modsuni/logic/commands/AddCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToDatabaseCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToStudentStagedCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToStudentTakenCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/GenerateCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromDatabaseCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromStudentStagedCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromStudentTakenCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveUserCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/SearchCommandTest.java
  src/test/java/seedu/modsuni/logic/parser/ModsUniParserTest.java
  src/test/java/seedu/modsuni/testutil/CredentialUtil.java
Labels: priority.High, status.readyToMerge, type.Code

#222 Bug fixes for Admin and Module database management
  src/main/java/seedu/modsuni/logic/PrereqGenerator.java
  src/main/java/seedu/modsuni/logic/commands/AddAdminCommand.java
  src/main/java/seedu/modsuni/logic/commands/AddModuleToDatabaseCommand.java
  src/main/java/seedu/modsuni/logic/commands/EditAdminCommand.java
  src/main/java/seedu/modsuni/logic/commands/EditModuleCommand.java
  src/main/java/seedu/modsuni/logic/commands/RemoveModuleFromDatabaseCommand.java
  src/main/java/seedu/modsuni/logic/commands/RemoveUserCommand.java
  src/main/java/seedu/modsuni/logic/commands/ShowUsernameCommand.java
  src/main/java/seedu/modsuni/logic/parser/ParserUtil.java
  src/test/java/seedu/modsuni/logic/PrereqGeneratorTest.java
  src/test/java/seedu/modsuni/logic/commands/AddAdminCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToDatabaseCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/EditAdminCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromDatabaseCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveUserCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/ShowUsernameCommandTest.java
Labels: bug, status.readyToReview, type.Code

#230 Bug fix for module storage
  src/main/java/seedu/modsuni/storage/XmlAdaptedAnd.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedModule.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedOr.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedPrereq.java
Labels: bug, priority.High, status.readyToMerge, type.Code

#269 Add switch tab command
  src/main/java/seedu/modsuni/logic/commands/SwitchTabCommand.java
  src/main/java/seedu/modsuni/logic/parser/CliSyntax.java
  src/main/java/seedu/modsuni/logic/parser/ModsUniParser.java
  src/main/java/seedu/modsuni/logic/parser/ParserUtil.java
  src/main/java/seedu/modsuni/logic/parser/SwitchTabCommandParser.java
  src/test/java/seedu/modsuni/logic/commands/CommandTestUtil.java
  src/test/java/seedu/modsuni/logic/commands/SwitchTabCommandTest.java
  src/test/java/seedu/modsuni/logic/parser/SwitchTabCommandParserTest.java
Labels: enhancement, priority.Medium, status.readyToMerge, status.readyToReview, type.UI

#268 Update save command to encrypt fields
  masterconfig
  masterconfig.xml
  src/main/java/seedu/modsuni/commons/util/DataSecurityUtil.java
  src/main/java/seedu/modsuni/logic/commands/LoginCommand.java
  src/main/java/seedu/modsuni/logic/commands/SaveCommand.java
  src/main/java/seedu/modsuni/model/Model.java
  src/main/java/seedu/modsuni/model/ModelManager.java
  src/main/java/seedu/modsuni/storage/StorageManager.java
  src/main/java/seedu/modsuni/storage/UserStorage.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedUser.java
  src/main/java/seedu/modsuni/storage/XmlSerializableUser.java
  src/main/java/seedu/modsuni/storage/XmlUserStorage.java
  src/test/data/XmlSerializableUserTest/validAdminUserData.xml
  src/test/data/XmlSerializableUserTest/validStudentUserData.xml
  src/test/java/seedu/modsuni/commons/util/DataSecurityUtilTest.java
  src/test/java/seedu/modsuni/logic/commands/AddCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToDatabaseCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToStudentStagedCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToStudentTakenCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/CommandTestUtil.java
  src/test/java/seedu/modsuni/logic/commands/GenerateCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromDatabaseCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromStudentStagedCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromStudentTakenCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveUserCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/SearchCommandTest.java
  src/test/java/seedu/modsuni/logic/parser/SaveCommandParserTest.java
  src/test/java/seedu/modsuni/storage/XmlAdaptedUserTest.java
  src/test/java/seedu/modsuni/storage/XmlSerializableUserTest.java
  src/test/java/seedu/modsuni/storage/XmlUserStorageTest.java
  src/test/java/seedu/modsuni/testutil/AdminBuilder.java
Labels: enhancement, priority.High, status.readyToReview

#267 Update UserGuide for mid v1.4
  docs/UserGuide.adoc
Labels: docs, status.readyToReview

#242 Added Test Cases & resolve outstanding issues for User Account Management
  src/main/java/seedu/modsuni/logic/commands/EditStudentCommand.java
  src/main/java/seedu/modsuni/logic/commands/RegisterCommand.java
  src/main/java/seedu/modsuni/logic/parser/AddAdminCommandParser.java
  src/main/java/seedu/modsuni/logic/parser/CliSyntax.java
  src/main/java/seedu/modsuni/logic/parser/EditStudentCommandParser.java
  src/main/java/seedu/modsuni/logic/parser/ParserUtil.java
  src/main/java/seedu/modsuni/logic/parser/RegisterCommandParser.java
  src/main/java/seedu/modsuni/model/credential/Credential.java
  src/main/java/seedu/modsuni/model/user/Admin.java
  src/main/java/seedu/modsuni/model/user/PathToProfilePic.java
  src/main/java/seedu/modsuni/model/user/User.java
  src/main/java/seedu/modsuni/model/user/student/Student.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedCredential.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedUser.java
  src/main/java/seedu/modsuni/ui/UserTab.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UserTab.fxml
  src/test/data/XmlSerializableCredentialStoreTest/typicalCredentialStore.xml
  src/test/java/guitests/guihandles/UserTabHandle.java
  src/test/java/seedu/modsuni/logic/commands/AddAdminCommandIntegrationTest.java
  src/test/java/seedu/modsuni/logic/commands/AddAdminCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/CommandTestUtil.java
  src/test/java/seedu/modsuni/logic/commands/EditStudentCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/modsuni/logic/commands/GenerateCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RegisterCommandIntegrationTest.java
  src/test/java/seedu/modsuni/logic/parser/EditStudentCommandParserTest.java
  src/test/java/seedu/modsuni/logic/parser/ParserUtilTest.java
  src/test/java/seedu/modsuni/logic/parser/RegisterCommandParserTest.java
  src/test/java/seedu/modsuni/model/user/PathToProfilePicTest.java
  src/test/java/seedu/modsuni/storage/XmlAdaptedCredentialTest.java
  src/test/java/seedu/modsuni/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/modsuni/testutil/StudentBuilder.java
  src/test/java/seedu/modsuni/testutil/StudentUtil.java
  src/test/java/seedu/modsuni/testutil/TypicalCredentials.java
  src/test/java/seedu/modsuni/testutil/TypicalUsers.java
  src/test/java/seedu/modsuni/ui/UserTabTest.java
Labels: priority.High, status.readyToMerge, type.Bug, type.Code

#285 Minor bug fix and Add test cases for v1.4
  src/main/java/seedu/modsuni/logic/PrereqGenerator.java
  src/main/java/seedu/modsuni/logic/commands/AddAdminCommand.java
  src/main/java/seedu/modsuni/logic/commands/AddModuleToDatabaseCommand.java
  src/main/java/seedu/modsuni/logic/commands/EditModuleCommand.java
  src/main/java/seedu/modsuni/logic/parser/AddModuleToDatabaseCommandParser.java
  src/main/java/seedu/modsuni/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/modsuni/logic/parser/ParserUtil.java
  src/main/java/seedu/modsuni/logic/parser/RemoveModuleFromDatabaseCommandParser.java
  src/main/java/seedu/modsuni/model/module/Code.java
  src/test/java/guitests/guihandles/UsernameCardHandle.java
  src/test/java/seedu/modsuni/logic/PrereqGeneratorTest.java
  src/test/java/seedu/modsuni/logic/parser/ParserUtilTest.java
  src/test/java/seedu/modsuni/logic/parser/RemoveModuleFromDatabaseCommandParserTest.java
  src/test/java/seedu/modsuni/model/module/CodeTest.java
  src/test/java/seedu/modsuni/ui/UsernameCardTest.java
  src/test/java/seedu/modsuni/ui/testutil/GuiTestAssert.java
Labels: status.readyToMerge

#283 Update UG/DG/PPP for v1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModuleDatabaseManagementDiagrams.pptx
  docs/diagrams/ModuleDatabaseManagementPictures.pptx
  docs/images/ADforModuleDatabaseAdministration.png
  docs/images/AddModuleToDatabaseCommandUML.png
  docs/images/EditModuleCommandExample.png
  docs/images/EditModuleCommandUML.png
  docs/images/RemoveModuleFromDatabaseCommandExample.png
  docs/images/RemoveModuleFromDatabaseCommandUML.png
  docs/team/deming.adoc
Labels: docs, status.readyToMerge

#288 Add testing, UI updating, and bug fixing
  data/credentialstore.xml
  src/main/java/seedu/modsuni/logic/parser/ShowModuleCommandParser.java
  src/main/java/seedu/modsuni/model/module/Code.java
  src/main/java/seedu/modsuni/model/util/SampleDataUtil.java
  src/main/java/seedu/modsuni/ui/BrowserPanel.java
  src/main/java/seedu/modsuni/ui/ModuleCard.java
  src/main/java/seedu/modsuni/ui/ModuleDisplay.java
  src/main/resources/view/ModuleDisplay.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/ModuleCardHandle.java
  src/test/java/guitests/guihandles/ModuleDisplayHandle.java
  src/test/java/seedu/modsuni/TestApp.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToStudentStagedCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/AddModuleToStudentTakenCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/CommandTestUtil.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromStudentStagedCommandTest.java
  src/test/java/seedu/modsuni/logic/commands/RemoveModuleFromStudentTakenCommandTest.java
  src/test/java/seedu/modsuni/logic/parser/ModsUniParserTest.java
  src/test/java/seedu/modsuni/logic/parser/ShowModuleCommandParserTest.java
  src/test/java/seedu/modsuni/testutil/ModuleUtil.java
  src/test/java/seedu/modsuni/testutil/TypicalModules.java
  src/test/java/seedu/modsuni/testutil/TypicalUsers.java
  src/test/java/seedu/modsuni/ui/DatabaseModuleListPanelTest.java
  src/test/java/seedu/modsuni/ui/StagedModuleListPanelTest.java
  src/test/java/seedu/modsuni/ui/TakenModuleListPanelTest.java
  src/test/java/seedu/modsuni/ui/UserTabTest.java
  src/test/java/seedu/modsuni/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddModuleToStudentStagedCommandSystemTest.java
  src/test/java/systemtests/AddModuleToStudentTakenCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
  src/test/java/systemtests/ModsUniSystemTest.java
  src/test/java/systemtests/RemoveModuleFromStudentStagedCommandSystemTest.java
  src/test/java/systemtests/RemoveModuleFromStudentTakenCommandSystemTest.java
  src/test/java/systemtests/SearchCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  test_8DB6604.xml
Labels: enhancement, status.readyToMerge, type.Code

#286 Update to Generate logic & Docs
  data/modules.xml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/GenerateCommandUML.pptx
  docs/images/GenerateCommandUML.png
  docs/images/generateErrorTip.png
  docs/images/generateMissingPrereq.png
  docs/images/generateMissingPrereqShow.png
  docs/images/generateMissingPrereqSuccess.png
  docs/images/generateMissingPrereqs.png
  docs/images/generateNoStagedModules.png
  docs/images/generateNoStagedModulesAdd.png
  docs/images/generateNoStagedModulesSuccess.png
  docs/images/generateSuccess.png
  docs/team/reubentan.adoc
  docs/team/rtjl.adoc
  src/main/java/seedu/modsuni/logic/Generate.java
  src/main/java/seedu/modsuni/logic/commands/GenerateCommand.java
  src/main/java/seedu/modsuni/model/ModelManager.java
  src/main/java/seedu/modsuni/model/module/Code.java
  src/main/java/seedu/modsuni/model/module/Module.java
  src/main/java/seedu/modsuni/model/module/Prereq.java
  src/main/java/seedu/modsuni/model/module/PrereqDetails.java
  src/main/java/seedu/modsuni/model/module/UniqueModuleList.java
  src/main/java/seedu/modsuni/model/semester/Semester.java
  src/main/java/seedu/modsuni/model/semester/SemesterList.java
  src/main/java/seedu/modsuni/storage/ModuleStorage.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedAnd.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedLockedModules.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedModule.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedOr.java
  src/main/java/seedu/modsuni/storage/XmlAdaptedPrereq.java
  src/test/java/seedu/modsuni/logic/commands/GenerateCommandTest.java
  src/test/java/seedu/modsuni/storage/XmlAdaptedModuleTest.java
  src/test/java/seedu/modsuni/storage/XmlAdaptedPrereqDetailsTest.java
Labels: docs, enhancement, priority.High, status.readyToMerge
